### ISSUE TITLE
Вёрстка

### ISSUE THREAD

**Issue by coder1x** [pepelsbey/pepelsbey.dev#1]
![изображение](https://user-images.githubusercontent.com/29002473/195022115-a8b9dd2b-aa44-4bd6-9125-08f9838a94e5.png)

Эти кнопки интерактивные, было бы не плохо добавить им cursor: pointer;

**Comment by coder1x** [comment]
![изображение](https://user-images.githubusercontent.com/29002473/195022572-9cd46c8d-3f0f-4e18-9caa-5523fa23faeb.png)

Тут стрелочка не кликабельная и то же нет cursor: pointer;  она просто находиться на уровне выше чем ссылка. Если стрелочке поставить z-index: 0; то всё будет ок.

**Comment by pepelsbey** [comment]
Я добавлю стрелке `pointer-events: none`, спасибо.

Насчёт кнопок — всё же не вижу в этом смысла. Это очевидная кнопка и в вашей ОС наверняка нет такого курсора на кнопках. Полосы прокрутки, текстовые поля, чекбоксы и лейблы форм тоже интерактивные, но мы не добавляем туда курсоры.

![image](https://user-images.githubusercontent.com/105274/195045220-de7d9bfd-21f3-41d7-a1c1-2f44d804a7ed.png)
