### ISSUE TITLE
Question about theme switcher and prefers-color-scheme

### ISSUE THREAD

**Issue by DmitryBerdnikov** [pepelsbey/pepelsbey.dev#13]
Hi, Vadim! I played with your theme switcher and found one case that I doubt.

When I open the site, theme is set as my system theme. And if I select a theme manually it replaces “prefers-color-scheme” with “all” or “not all” depending on the theme I selected, expected behavior.

But then if I reload the page, the media query is set as “prefers-color-scheme” if site’s theme is equal to my system theme.

![Group 1008](https://user-images.githubusercontent.com/32369609/219842728-6944c560-b1d7-42c2-8019-c5c0a605af8d.jpg)

For me, it works like auto option, but I selected specific theme. And if I change my system theme while the site is open, the theme switches automaically, but the switcher points to the previous theme.

![Group 1009](https://user-images.githubusercontent.com/32369609/219842795-7f5e2a10-759d-4a81-91f4-170f4ebb9ea7.png)

My question: maybe it's better to set the media query without "prefers-color-scheme" when opening the site if the user has manually selected a theme?

**Comment by pepelsbey** [comment]
Hey! When the switcher is set to any option apart from auto, it means “manual override”. Meaning that no matter what you’re changing in your system settings, it will remain the same. And it reflects how the switcher works: it saves the state to the localStorage. The use case for this is when a user has light/dark themes in their OS switched automatically depending on the time of the day, but they prefer to read my website using a specific theme. I hope I got your idea right.

**Comment by DmitryBerdnikov** [comment]
Thanks for the detailed explanation!

Yes, I get the idea. But maybe I didn't explain clearly.

I will give an example, let's imagine the following case:
The user's OS theme changes depending on the time of day (light theme: from 9am untill 7pm and dark theme: from 7pm until 9am). But the user wants to read your website only in the dark theme. Then the user manually select dark theme.

One day at 8:50 am the user opens your website with OS dark theme and the theme in your website is dark, it’s expected. But the media query has "prefers-color-scheme" value (my first screenshot [here](https://github.com/pepelsbey/pepelsbey.dev/issues/13#issue-1590215553).)
But at 9:01 the OS theme switches to light theme and your website switches to light theme too, but the user has overridden theme with dark. It is not expected for me.

It happens because of [this if condition](https://github.com/pepelsbey/pepelsbey.dev/blob/4a2cec737283e320b035495802f66dd2d76295ed/src/scripts/modules/theme-switcher.js#L41). I can record a small demo, if it's needed.

And if you agree with my idea, I can create PR to remove the if condition

**Comment by pepelsbey** [comment]
Hmm, I still don’t get it: on the video, I force a certain theme and then try to change the system settings (just like the sunrise/sunset would) and can’t change the theme because it’s forced. This is exactly how I’d like it to work :)

https://user-images.githubusercontent.com/105274/219876259-436438e8-0a52-4842-9755-2fe61fb20889.mp4

**Comment by pepelsbey** [comment]
But! I see that something’s not right with your screenshot: if dark is forced, then the value is supposed to be `not all`/`all`. But for some reason, it’s not. So you’re probably right! Please send PR :)

**Comment by pepelsbey** [comment]
Oh, right. I think I can see it now: if the system theme differs from the forced one, it doesn’t stay forced on page load. Or something like that 😅

**Comment by pepelsbey** [comment]
Yep, here it is: I force dark, then reload. The switcher is still dark, but the website’s theme follows the system one when I switch it to light. Dammit! 😆

https://user-images.githubusercontent.com/105274/219877158-9c417fb7-19cb-42c2-9104-f406541d66a9.mp4

**Comment by DmitryBerdnikov** [comment]
I created PR #14

**Comment by pepelsbey** [comment]
Fixed in #14, thanks!
