### ISSUE TITLE
Едет верстка в некоторых статьях

### ISSUE THREAD

**Issue by maxdenaro** [pepelsbey/pepelsbey.dev#18]
Привет! На ширине вьюпорта ниже 375px в некоторых статьях едет верстка. Вероятно, в этих статьях контенту не хватает места.

Например, тут https://pepelsbey.dev/articles/jumping-html-tags/

**Comment by pepelsbey** [comment]
Привет! Спасибо за репорт. Можно ли подробнее? Скриншот, версия браузера, платформа. Это сильно поможет найти и исправить. Разум вы это знаете и видели. Спасибо!

**Comment by maxdenaro** [comment]
На реальном мобильном устройстве, к счастью, проблемы нет (хотя я не тестил вообще все). 

А вот если смотреть через инспектор кода в браузере на пк (Windows 11, Chrome последней версии), получаем это:
![image](https://github.com/pepelsbey/pepelsbey.dev/assets/25548841/3f2ccc62-557e-4ecc-a9ee-07d22de58159)

Это, безусловно, мелочь, раз на реальном устройстве все в порядке, но все же. Проблема в данной ссылке:

`<a href="https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags">https://www.w3.org/TR/html5/syntax.html</a>`

**Comment by pepelsbey** [comment]
[Починил](https://github.com/pepelsbey/pepelsbey.dev/commit/abff37c6b2758404bc630ab88d7ea6c621b68998), спасибо!
