### ISSUE TITLE
H1 in desktop articles is too big when title is long

### ISSUE THREAD

**Issue by WEBPerformace** [pepelsbey/pepelsbey.dev#6]
Something tells me that it's not OK when H1 does not fit on a full screen page on the desktop.

![image](https://user-images.githubusercontent.com/121736447/210666866-66ba1a6f-0693-4d69-a6e8-2c97ccf17a3a.png)

**Comment by pepelsbey** [comment]
It doesn’t look too bad for me, to be honest. I know it’s a bit unusual, but I like this style.

I might get back to it if I hear more feedback like this. Thanks!
